services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: civ-copilot-client:dev
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: civ-copilot-api:dev
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    working_dir: /app
    env_file:
      - ./server/.env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: civ-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
